version: '3'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5001:5001"
    volumes:
      - backend_data:/app/instance
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    networks:
      - app-network

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_API_BASE_URL=http://localhost:5001
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  backend_data:

networks:
  app-network:
    driver: bridge 